title: 'Stencila'
baseURL: 'https://stenci.la'
contentDir: './content'
enableRobotsTXT: true
relativeURLs: true
sectionPagesMenu: 'main'
enableEmoji: true

permalinks:
  blog: /:section/:filename

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
  highlight:
    style: manni

frontmatter:
  date:
    - ':default'
    - ':filename'
  publishDate:
    - ':default'
    - ':filename'
